# Site settings
title: Dowsnux
email: fco.anjos@gmail.com
description: "A Dowsnux é uma jovem empresa de desenvolvimento e manutenção de sistemas corporativos e aplicativos móveis. Oferecemos serviços personalizados em desenvolvimento de aplicativos móveis, de sites e consultoria para sistemas corporativos. Acreditamos na prestação dos serviços sem comprometer o tempo e a qualidade, e em consequência, proporcionam crescimento ao seu negócio."

# Team names, titles and social links
people:
- name: Francisco Tavares
  pic: 1
  position: Lead Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/fcoanjos/
    - title: github
      url: https://github.com/FranciscoTavares
    - title: twitter
      url: https://twitter.com/fcoanjos

- name: Gerviz Holanda
  pic: 2
  position: Systems Analyst
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/gerviz-holanda-de-azevedo-junior-856649b0/

- name: Jonathas Batista
  pic: 3
  position: Lead Designer
  social:
    - title: facebook
      url: https://www.facebook.com/jonathas.batista.7

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/fcoanjos
  - title: facebook
    url: https://www.facebook.com/Hyperlinkinfosystem
  - title: github
    url: http://github.com/FranciscoTavares
  - title: instagram
    url: https://www.instagram.com/ftavares512/

# Postal address (add as many lines as necessary)
address:
  - line: Alameda Dr. Carlos de Carvalho, 771
  - line: Bigorrilho, Curitiba

# Build settings
markdown: kramdown
permalink: pretty
